List<String> fishlist = [
  "Salimov Davlat",
  "Karimov Shavkat",
  "To'raev Mirjalol",
  "Bektemirov Alisher",
  "Abdullayev Javohir",
  "Rustamov Otabek",
  "Norqobilov Davron",
  "Saidov Oybek",
  "Ismoilov Bobur",
  "Azimov Sardor",
  "Ergashev Alimardon",
  "Sobirov Jaloliddin",
  "Mahmudov Doston",
  "Hakimov Jamshid",
  "Yuldashev Bekzod",
  "Khaydarov Zafar",
  "Shukurov Aziz",
  "Qo'ziev Umar",
  "Rasulov Farrukh",
  "Beknazarov Mirzohid",
  "Orifov Shamsiddin",
  "Usmonov Muzaffar",
  "Rahmonov Dilshod",
];
